CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
CCC                                                                     CCC
CCC                    SUBROUTINE NEWGEN                                CCC
CCC                                                                     CCC
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      SUBROUTINE NEWGEN(ID,IDMASTER,NPRO,IGEN,IG,ILOAD,UNDAT,UNOUT)
C
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
C
      INCLUDE 'PGA_Parameters.h'
      INCLUDE 'mpif.h'
C
      COMMON/PGAINFO/NGEN,NPOP,NPAR,NBIT(NPARMAX)
      COMMON/PGAMUTA/PJMU,PCMU
      COMMON/PARINFO/PARMIN(NPARMAX),PARMAX(NPARMAX),PARRES(NPARMAX)
      COMMON/PARAMET/PARAM(NPARMAX,NPOPMAX)
      COMMON/NEWGENE/CHILD(NPARMAX,NPOPMAX)
      COMMON/FITNESS/FITNESS(NPOPMAX),PSEL(NPOPMAX),JBEST
C
      INTEGER ID,IDMASTER,NPRO,IERR
C
      REAL*8 PAR(NPARMAX)
      INTEGER IPAR(NPARMAX*NBITMAX)
      INTEGER IGEN,IG
      INTEGER ILOAD(MAXPROC,NPOPMAX)
      INTEGER STATUS(MPI_STATUS_SIZE)
      INTEGER UNDAT,UNOUT
C
      INTEGER IDUMMY
C
C**************************************************************************
C
      IF (ID.EQ.IDMASTER) THEN
C
C     WRITE BEST PARENT TO FILE
C
       WRITE(UNOUT,100) IGEN+IG,FITNESS(JBEST),(PARAM(I,JBEST),I=1,NPAR)
  100  FORMAT (I6,2X,E10.4,2X,200(E12.6,1X))
C
C      SET LAST CHILD AS BEST PARENT
C
       DO I=1,NPAR
        CHILD(I,NPOP)=PARAM(I,JBEST)
       END DO
C
C      SWITCH TO NEW GENERATION
C
       DO J=1,NPOP
        DO I=1,NPAR
         PARAM(I,J)=CHILD(I,J)
        END DO
       END DO
C
C      WRITE CURRENT POPULATION TO DATA FILE    
C
       OPEN (UNDAT,FILE='Model/PGA.dat')
       WRITE (UNDAT,'(I6)') IGEN+IG
       DO J=1,NPOP
        WRITE (UNDAT,'(I3,2X,200(E14.8,1X))') J,(PARAM(I,J),I=1,NPAR)
       END DO
       CLOSE (UNDAT)
C
      END IF
C
C     BROADCAST PARAMETERS OVER CLUSTER
C
      CALL MPI_BCAST(IDUMMY,1,MPI_INTEGER,IDMASTER,MPI_COMM_WORLD,IERR)
C
      DO J=1,NPOP
       IF (ID.EQ.IDMASTER) THEN
        IF (ILOAD(ID+1,J).EQ.0) THEN
         DO I=1,NPAR
          PAR(I)=PARAM(I,J)
         END DO
         K=0
         DO N=1,NPRO
          IF (ILOAD(N,J).EQ.1) K=N-1
         END DO
         CALL MPI_SEND(PAR,NPAR,MPI_DOUBLE_PRECISION,K,J,
     &                 MPI_COMM_WORLD,IERR)
        END IF
       ELSE
        IF (ILOAD(ID+1,J).EQ.1) THEN
         CALL MPI_RECV(PAR,NPAR,MPI_DOUBLE_PRECISION,IDMASTER,
     &                 MPI_ANY_TAG,MPI_COMM_WORLD,STATUS,IERR)
         DO I=1,NPAR
          PARAM(I,J)=PAR(I)
         END DO
        END IF
       END IF
      END DO
C
      CALL MPI_BCAST(IDUMMY,1,MPI_INTEGER,IDMASTER,MPI_COMM_WORLD,IERR)
C
C**************************************************************************
C
      RETURN
C
      END
