C
C     LEVEL-SET INITIAL VALUES
C
      COMMON/LEVINI/SINI(NRMAX)
C
C     LEVEL-SET BOUNDARY CONDITIONS
C
      COMMON/LEVBCO/KS(NBMAX,NRMAX),GS(NBMAX,3,NRMAX)
C
C     LEVEL-SET FIELD
C
      COMMON/LEVFIT/SCC(NCMAX,NRMAX),D2S(NCMAX,NRMAX)
     &             ,DXS(NCMAX,NRMAX),DYS(NCMAX,NRMAX)