C
C     MOMENTUM/STRUCTURAL INITIAL VALUES
C
      COMMON/MOMINI/UINI(NRMAX),VINI(NRMAX)
C
C     MOMENTUM/STRUCTURAL BODY FORCES
C
      COMMON/MOMBOF/FBX(NRMAX),FBY(NRMAX)
C
C     MOMENTUM/STRUCTURAL BOUNDARY CONDITIONS
C
      COMMON/MOMBCO/KM(NBMAX,NRMAX),GU(NBMAX,3,NRMAX)
     &                             ,GV(NBMAX,3,NRMAX)
     &                             ,GH(NBMAX,3,NRMAX)
C
C     MOMENTUM/STRUCTURAL FIELD
C
      COMMON/MOMFIU/UCC(NCMAX,NRMAX),D2U(NCMAX,NRMAX)
     &             ,DXU(NCMAX,NRMAX),DYU(NCMAX,NRMAX)
      COMMON/MOMFIV/VCC(NCMAX,NRMAX),D2V(NCMAX,NRMAX)
     &             ,DXV(NCMAX,NRMAX),DYV(NCMAX,NRMAX)
C
C     MOMENTUM/STRUCTURAL DILATATION
C
      COMMON/MOMFID/DCC(NCMAX,NRMAX),DTD(NCMAX,NRMAX)