C
C     ENERGY INITIAL VALUES
C
      COMMON/ENEINI/TINI(NRMAX)
C
C     ENERGY BODY FORCES
C
      COMMON/ENEBOF/UBG(NRMAX)
C
C     ENERGY BOUNDARY CONDITIONS
C
      COMMON/ENEBCO/KE(NBMAX,NRMAX),GT(NBMAX,3,NRMAX)
C
C     ENERGY FIELD
C
      COMMON/ENEFIT/TCC(NCMAX,NRMAX),D2T(NCMAX,NRMAX)
     &             ,DXT(NCMAX,NRMAX),DYT(NCMAX,NRMAX)