C
C     PORE PRESSURE INITIAL VALUES
C
      COMMON/PORINI/PINI(NRMAX)
C
C     PORE PRESSURE BODY FORCES
C
      COMMON/PORBOF/QBG(NRMAX)
C
C     PORE PRESSURE BOUNDARY CONDITIONS
C
      COMMON/PORBCO/KP(NBMAX,NRMAX),GP(NBMAX,3,NRMAX)
C
C     PORE PRESSURE FIELD
C
      COMMON/PORFIT/PCC(NCMAX,NRMAX),D2P(NCMAX,NRMAX)
     &             ,DXP(NCMAX,NRMAX),DYP(NCMAX,NRMAX)
C
C     PORE PRESSURE VELOCITY
C
      COMMON/PORFIV/VFX(NCMAX,NRMAX),VFY(NCMAX,NRMAX)