C
C     NUMBER OF REGIONS AND POINTS
C
      COMMON/INFORM/NR,NB(NRMAX),NI(NRMAX),NC(NRMAX)
C
C     GEOMETRY
C
      COMMON/GEOMET/XC(NCMAX,NRMAX),YC(NCMAX,NRMAX)
      COMMON/NORMAL/XN(NBMAX,NRMAX),YN(NBMAX,NRMAX)
      COMMON/BYAREA/AR(NBMAX,NRMAX)