C
C     SOLUTION FLAGS
C
      COMMON/MSOLUT/MSM,MSS,MSE,MSP,MSL
C
C     TIME STEP AND CURRENT TIME
C
      COMMON/TRANSI/DT,CTIME
C
C     ITERATION PARAMETERS
C
      COMMON/ITERAT/MAXITER,ITP,IWRITE,IRES,ISUB
C
C     RELAXATION PARAMETERS
C
      COMMON/RELAXA/THP,THU,THI
C
C     GRAVITY
C
      COMMON/GRAVIT/GX,GY
C
C     RESIDUALS
C
      COMMON/RESIDU/RESC,RESX,RESY,RESE
      COMMON/RESIDL/RESL,RESU,RESV,RESP