C
C     FIRST-ORDER UPWINDING INTERPOLATION VECTORS
C
      COMMON/FIRXEW/FXE(NCMAX,NFMAX,NRMAX),FXW(NCMAX,NFMAX,NRMAX)
      COMMON/FIRYNS/FYN(NCMAX,NFMAX,NRMAX),FYS(NCMAX,NFMAX,NRMAX)
C
C     SECOND-ORDER UPWINDING INTERPOLATION VECTORS
C
      COMMON/SECXEW/SXE(NCMAX,NFMAX,NRMAX),SXW(NCMAX,NFMAX,NRMAX)
      COMMON/SECYNS/SYN(NCMAX,NFMAX,NRMAX),SYS(NCMAX,NFMAX,NRMAX)