C
C     CENTRAL DIFFERENCE INTERPOLATION VECTORS
C
      COMMON/CENDIF/FXC(NCMAX,NFMAX,NRMAX),FYC(NCMAX,NFMAX,NRMAX)
C
      COMMON/CENDIS/FXX(NCMAX,NFMAX,NRMAX),FYY(NCMAX,NFMAX,NRMAX)
     &             ,FXY(NCMAX,NFMAX,NRMAX)