C
C     MATERIAL TYPE
C
      COMMON/KRTYPE/KR(NRMAX)
C
C     FLUID PROPERTIES
C
      COMMON/FLUDEN/DEF(NRMAX)
      COMMON/FLUSSR/VIF(NRMAX),POF(NRMAX)
      COMMON/FLUENE/TCF(NRMAX),SHF(NRMAX)
      COMMON/FLUTEX/BEF(NRMAX),TRF(NRMAX)
      COMMON/FLUCOM/COF(NRMAX)
C
C     SOLID PROPERTIES
C
      COMMON/SOLDEN/DES(NRMAX)
      COMMON/SOLSSR/VIS(NRMAX),POS(NRMAX)
      COMMON/SOLENE/TCS(NRMAX),SHS(NRMAX)
      COMMON/SOLTEX/BES(NRMAX),TRS(NRMAX)
      COMMON/SOLPOR/PER(NRMAX),POR(NRMAX)
C
C     EFFECTIVE PROPERTIES
C
      COMMON/EFFDEN/DEE(NRMAX)
      COMMON/EFFSSR/VIE(NRMAX),POE(NRMAX)
      COMMON/EFFENE/TCE(NRMAX),SHE(NRMAX)
      COMMON/EFFTEX/BEE(NRMAX),TRE(NRMAX)