C
C     ALMA PARAMETER FILE
C
C     PI      :   VALUE OF PI
C     EPS     :   SMALL VALUE
C     NDIM	:	NUMBER OF PHYSICAL DIMENSIONS
C     NPMAX   :   MAXIMUM NUMBER OF CLUSTER PROCESSORS
C     NRMAX   :   MAXIMUM NUMBER OF REGIONS
C     NBMAX   :   MAXIMUM NUMBER OF BOUNDARY POINTS PER REGION
C     NCMAX   :   MAXIMUM NUMBER OF TOTAL POINTS PER REGION
C     NFMAX   :   MAXIMUM NUMBER OF INFLUENCE POINTS PER TOPOLOGY
C     NEMAX   :   MAXIMUM NUMBER OF ADDITIONAL POLYNOMIAL TERMS PER TOPOLOGY
C     NSMAX   :   MAXIMUM NUMBER OF PREPROCESSOR SEGMENTS PER REGION
C     NNS     :   NUMBER OF NODES PER SEGMENT
C
      PARAMETER (PI=3.1415926535897932384626433832795D+000)
      PARAMETER (EPS=1.D-020)
      PARAMETER (NDIM=2)
      PARAMETER (NPMAX=16)
      PARAMETER (NRMAX=2)      
      PARAMETER (NBMAX=1000)
      PARAMETER (NCMAX=20000)
      PARAMETER (NFMAX=49)
      PARAMETER (NEMAX=10)
      PARAMETER (NSMAX=40)
      PARAMETER (NNS=3)