C
C     PREPROCESSOR SEGMENTS
C
      COMMON/SEGNUM/NS(NRMAX),NPS(NSMAX,NRMAX)
      COMMON/SEGGEO/XS(NSMAX,NNS,NRMAX),YS(NSMAX,NNS,NRMAX)
C
C     INTERNAL POINT DISTRIBUTION
C
      COMMON/SEGINT/NIR(NRMAX),NIX(NSMAX,NRMAX)   ,NIY(NSMAX,NRMAX)
     &                        ,XIMIN(NSMAX,NRMAX) ,YIMIN(NSMAX,NRMAX)
     &                        ,XIMAX(NSMAX,NRMAX) ,YIMAX(NSMAX,NRMAX)